#!/usr/bin/env node
// =====================================================================
//  embed-assets.mjs
//
//  Converts the device-target Vite build output (dist-device/) into a
//  single C++ header consumed by the firmware. Each file becomes a static
//  byte array (gzip-compressed for size + Content-Encoding); a routing
//  table maps URL paths to {data, length, mime, gzip}.
//
//  Usage:   npm run build:device && npm run embed
//  Output:  ../smart_knob_shifter/src/system/EmbeddedAssets.h
// =====================================================================

import { promises as fs } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { resolve, relative, join, posix, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT     = resolve(__dirname, '..');
const DIST     = resolve(ROOT, 'dist-device');

// We emit the header into the firmware tree. Adjust this path if the repo
// layout changes — both R&D and AXIS clones need a final rsync to receive it.
const OUT_HDR  = resolve(ROOT, '../smart_knob_shifter/src/system/EmbeddedAssets.h');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.webmanifest': 'application/manifest+json',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
  '.txt':  'text/plain; charset=utf-8',
  '.map':  'application/json'           // we'll usually skip these
};

const SKIP_EXTS = ['.map'];              // sourcemaps inflate flash for zero gain

// Folders under dist-device/ that should NEVER end up embedded — they exist
// only for the GitHub Pages mirror of the PWA. firmware/ holds OTA .bin files
// (1.5 MB each) which would otherwise blow past the device's flash budget.
const SKIP_DIRS = new Set(['firmware']);

/** Walk a directory, return absolute paths to every file. */
async function walk(dir, relPrefix = '') {
  const out = [];
  for (const ent of await fs.readdir(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(ent.name) && relPrefix === '') continue;   // top-level only
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      out.push(...(await walk(full, relPrefix + ent.name + '/')));
    } else {
      out.push(full);
    }
  }
  return out;
}

/** Turn a path like "/assets/index-ab12.js" into a valid C identifier. */
function ident(urlPath) {
  return 'asset_' + urlPath.replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '');
}

function extOf(p) {
  const m = p.match(/\.[^.]+$/);
  return m ? m[0].toLowerCase() : '';
}

function formatBytes(buf) {
  const parts = [];
  for (let i = 0; i < buf.length; ++i) {
    parts.push('0x' + buf[i].toString(16).padStart(2, '0'));
    if (parts.length && parts.length % 16 === 0) parts[parts.length - 1] += ',\n  ';
    else if (i < buf.length - 1) parts[parts.length - 1] += ',';
  }
  return '  ' + parts.join(' ');
}

async function main() {
  let totalRaw = 0, totalGz = 0;
  const files = (await walk(DIST))
    .filter(p => !SKIP_EXTS.includes(extOf(p)))
    .sort();

  if (files.length === 0) {
    console.error(`No files in ${DIST}. Did you run \`npm run build:device\`?`);
    process.exit(1);
  }

  let body = '';
  const entries = [];

  for (const abs of files) {
    const rel  = '/' + relative(DIST, abs).split(posix.sep).join('/');
    const buf  = await fs.readFile(abs);
    const gz   = gzipSync(buf, { level: 9 });
    const mime = MIME[extOf(rel)] ?? 'application/octet-stream';
    const id   = ident(rel);

    body += `// ${rel}  (${buf.length}B raw → ${gz.length}B gz)\n`;
    body += `static const uint8_t ${id}[] PROGMEM = {\n`;
    body += formatBytes(gz);
    body += `\n};\n\n`;

    entries.push({ rel, id, len: gz.length, mime });
    totalRaw += buf.length;
    totalGz  += gz.length;
  }

  let table = `struct EmbeddedAsset { const char* path; const uint8_t* data; size_t len; const char* mime; };\n\n`;
  table += `static const EmbeddedAsset kEmbeddedAssets[] = {\n`;
  for (const e of entries) {
    table += `  { "${e.rel}", ${e.id}, ${e.len}, "${e.mime}" },\n`;
  }
  table += `};\n`;
  table += `static constexpr size_t kEmbeddedAssetCount = sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);\n`;

  const out =
`// =========================================================================
// AUTO-GENERATED by tools/embed-assets.mjs in the axis-companion repo.
// DO NOT EDIT BY HAND — re-run \`npm run build:device && npm run embed\`.
//
// Sources : dist-device/ (Vite production build, device target)
// Total   : ${files.length} files, ${totalRaw}B raw → ${totalGz}B gzip
// =========================================================================
#pragma once
#include <Arduino.h>
#include <pgmspace.h>

${body}
${table}
`;

  await fs.mkdir(dirname(OUT_HDR), { recursive: true });
  await fs.writeFile(OUT_HDR, out);

  console.log(`Wrote ${OUT_HDR}`);
  console.log(`  ${files.length} files, ${totalRaw} B raw → ${totalGz} B gz`);
}

main().catch(e => { console.error(e); process.exit(1); });
